#!/bin/bash

# Script d'information pour MySQL sans Docker
echo "🗄️  Configuration MySQL sans Docker"
echo ""
echo "🔧 Options pour démarrer MySQL :"
echo ""
echo "1️⃣  XAMPP (Windows/Mac/Linux)"
echo "   - Télécharger : https://www.apachefriends.org/"
echo "   - Démarrer le panneau XAMPP"
echo "   - Cliquer sur 'Start' pour MySQL"
echo ""
echo "2️⃣  WAMP (Windows)"
echo "   - Télécharger : https://www.wampserver.com/"
echo "   - Démarrer WampServer"
echo "   - MySQL démarre automatiquement"
echo ""
echo "3️⃣  MAMP (Mac)"
echo "   - Télécharger : https://www.mamp.info/"
echo "   - Démarrer MAMP"
echo "   - Cliquer sur 'Start Servers'"
echo ""
echo "4️⃣  Installation native"
echo "   # Windows (avec Chocolatey)"
echo "   choco install mysql"
echo ""
echo "   # macOS (avec Homebrew)"
echo "   brew install mysql"
echo "   brew services start mysql"
echo ""
echo "   # Ubuntu/Debian"
echo "   sudo apt update"
echo "   sudo apt install mysql-server"
echo "   sudo systemctl start mysql"
echo ""
echo "5️⃣  MySQL en ligne"
echo "   - PlanetScale : https://planetscale.com/"
echo "   - Railway : https://railway.app/"
echo "   - Aiven : https://aiven.io/"
echo ""
echo "📋 Configuration requise :"
echo "   Host: localhost (ou IP du serveur)"
echo "   Port: 3306"
echo "   Database: taxibiker_dev"
echo "   Username: root (ou votre utilisateur)"
echo "   Password: (votre mot de passe)"
echo ""
echo "⚙️  Après avoir démarré MySQL :"
echo "   1. Créer la base de données 'taxibiker_dev'"
echo "   2. Configurer .env.local avec vos paramètres"
echo "   3. Exécuter : ./scripts/start-backend.sh"
echo ""
echo "💡 Exemple de configuration .env.local :"
echo "   DATABASE_URL=mysql://root:password@127.0.0.1:3306/taxibiker_dev?serverVersion=8.0&charset=utf8mb4"
