#!/bin/bash

# Script d'information pour arrêter MySQL sans Docker
echo "🛑 Arrêt de MySQL sans Docker"
echo ""
echo "🔧 Comment arrêter MySQL selon votre installation :"
echo ""
echo "1️⃣  XAMPP"
echo "   - Ouvrir le panneau XAMPP"
echo "   - Cliquer sur 'Stop' pour MySQL"
echo ""
echo "2️⃣  WAMP"
echo "   - Clic droit sur l'icône WAMP"
echo "   - MySQL > Service > Stop Service"
echo ""
echo "3️⃣  MAMP"
echo "   - Ouvrir MAMP"
echo "   - Cliquer sur 'Stop Servers'"
echo ""
echo "4️⃣  Installation native"
echo "   # Windows (Services)"
echo "   net stop mysql80"
echo ""
echo "   # macOS (Homebrew)"
echo "   brew services stop mysql"
echo ""
echo "   # Linux (systemd)"
echo "   sudo systemctl stop mysql"
echo ""
echo "5️⃣  Ligne de commande MySQL"
echo "   mysqladmin -u root -p shutdown"
echo ""
echo "💡 Pour vérifier si MySQL est arrêté :"
echo "   # Tenter une connexion (doit échouer)"
echo "   mysql -u root -p"
echo ""
echo "   # Ou vérifier les processus"
echo "   # Windows : tasklist | findstr mysql"
echo "   # Linux/Mac : ps aux | grep mysql"
